# Generated by Django 3.2.4 on 2021-06-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('subscription_type', models.CharField(max_length=20)),
            ],
        ),
    ]
